name: Deploy Ruby CodeStyle

on:
  push:
    branches:
      - main
    paths:
      - ruby/**

jobs:
  build:
    name: Ruby ${{matrix.ruby}}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        ruby: ["2.4", "2.7", "3.0"]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ${{ github.workspace }}/ruby
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/ruby
        run: |
          gem install bundler
          bundle install
      - name: Run Tests
        working-directory: ${{ github.workspace }}/ruby
        run: | # add more tests as necessary in rake file. Make sure they pass before PR
          bundle exec rake
